### ISSUE TITLE
按教程执行操作后无反应

### ISSUE THREAD

**Issue by wolffy1998** [lyc8503/BilibiliDailyBonus#2]
根据教程执行后没有效果，也没收到邮箱回复

**Comment by lyc8503** [comment]
我看了你 Fork 的项目, 设置是对的. 程序不是立即执行的, 每天早上八点会自动执行.

**Comment by lyc8503** [comment]
而且现在 B 站官方修改了活动, 奖品有所更改, 而且不是 100% 中奖, 但抽奖还是能正常进行的, 如果中奖 B 站会直接给你通知的.

**Comment by wolffy1998** [comment]
收到
